apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-webapp
resources:
  - service.yaml
  - deployment.yaml
  - pvc.yaml
  - ingress.yaml
  - configmap.yaml
  - namespace.yaml
  - secret.yaml
